- package.json
- src/main.tsx
- src/styles/GlobalStyle.tsx
- yarn.lock
close #9 
- GlobalStyle 추가
- styled-reset을 지우고 emotion-reset을 추가했습니다
- npm i 해주세요!
> init: emotion/reset 추가

- src/components/common/Category/Category.styles.tsx
- src/components/common/Category/Category.tsx
- src/components/common/commonUiTest/CategoryTest.tsx
close #14 
https://github.com/supercoding-commerce/FE/assets/100771469/a8f947c9-cbf5-428d-a9c8-007d789c88be
아래의 단계를 거쳐
카테고리 공동 ui 작업했습니다.
1. icon,title,option을 받아서 렌더링
2. 클릭했을때 색 변함
3. 다시 클릭했을때 색 원상복귀
4. topOption 클릭했을때 해당 subOption 나타내기
5. 먼저 하드코딩으로 옵션 정보가 잘 나타나는지 확인
6. 확인된 옵션을 props로 전달해보기
자세한 사용 예시는
CategoryTest.tsx 파일을 확인해주세요!
https://github.com/supercoding-commerce/FE/assets/100771469/95cd6fd2-b903-403e-a70f-886ce9639e82
카테고리 공동 컴포넌트로 서비스 카테고리 작업 해주시는 분께서 사용하실 때
카테고리에서 상위 옵션에는 하위 컴포넌트를 보여주는 로직 이외의 기능이 필요하실지도 몰라서
공동컴포넌트 clickHandle함수에 원하시는 추가 로직을 props로 전달할 수 있는 틀을 만들었습니다.
테스트 했을때 props로 기능이 전달되는것도 확인했으나,
혹시나 props로 기능 전달이 안되면 말씀 부탁드립니다.
> feat:#14 카테고리 컴포넌트 완료

- src/components/common/Button/Button.styles.tsx
버튼 컴포넌트에 폰트 스타일 적용 누락
버튼 사이즈마다 폰트 크기, 스타일이 동일해서 size에 theme.font 추가 했습니다.
> refactor:#44 button 공동컴포넌트 theme 폰트 추가

- src/components/chat/chatDetail/ChatRightBox.tsx
ChatRightBox.tsx에서 React import 부분 삭제
> remove:import React

- src/components/common/SelectBox/SelectBox.styles.tsx
close #56 
- SelectBox 옵션들의 배경색을 white로 추가
> fix : selectbox 버그 수정

- src/components/chat/Chat.tsx
> refactor:필요없는 주석,console 제거

- src/components/chat/Chat.styles.tsx
- src/components/chat/Chat.tsx
- src/components/chat/chatDetail/ChatDetailBody.tsx
- src/components/chat/chatDetail/ChatDetailHeader.tsx
- src/components/chat/chatDetail/ChatLeaveBox.tsx
- vite.config.ts
message type이 'LEAVE'일때 
message type이 'TERMINATE'일때 완료
https://github.com/supercoding-commerce/FE/assets/100771469/da608851-8fd9-45ea-a85f-998ca23903b8
<br/>
<br/>
> feat:#69 message type이 'LEAVE'일때, message type이 'TERMINATE'일때 완료

- src/components/chat/Chat.tsx
- src/components/chat/chatDetail/ChatDetailBody.tsx
- src/components/chat/chatDetail/ChatDetailHeader.tsx
- src/components/chat/chatDetail/ChatDetailIntro.tsx
> feat:#76 상단에 shop name 표시하기 완료

- src/components/chat/Chat.styles.tsx
- src/components/chat/chatDetail/ChatSend.tsx
> refactor:#78 chat detailpage 일그러진 css 수정 완료

- src/components/Detail/Detail.styles.tsx
- src/components/Detail/detailCategory/DetailCategory.tsx
- src/components/Detail/detailInformation/InformationBox.tsx
- src/components/Detail/detailReview/ReviewBox.tsx
- src/components/Detail/detailReview/ReviewButton.tsx
- src/components/Detail/detailReview/ReviewFilterButton.tsx
- src/components/Detail/detailReview/ReviewWrite.tsx
- src/pages/routes.tsx
> feat:#50 detail page ui 작업(리뷰, 상세 디테일) 완료

- src/components/common/Header/SearchHeader.tsx
close #83 
- 헤더 로그인 기능 및 상태 추가
- 유저별 페이지 이동
> feat : header 로그인기능 구현

- src/components/chat/Chat.styles.tsx
- src/components/chat/Chat.tsx
- src/components/chat/ChatDetail.tsx
- src/components/chat/chatDetail/ChatDetailHeader.tsx
- src/main.tsx
1. 채팅방 헤더 오른쪽에 x버튼 추가 완료
2. x버튼 누르면 창닫기 완료
https://github.com/supercoding-commerce/FE/assets/100771469/4da8d2fc-9f4b-4435-a693-c5f893542a21
디테일페이지에서 버튼 추가해서 클릭하면 여는것도 구현해야 합니다.
> feat:#93 chat 채팅창 x버튼 추가완료

- src/App.tsx
- src/components/chat/Chat.tsx
- src/components/chat/ChatList.tsx
close #103 
1. chatList 판매자일때 분기처리 완료
2. chatList 유저일때 분기처리 완료
1. chatList 판매자일때 분기처리 완료
https://github.com/supercoding-commerce/FE/assets/100771469/6b36f4c2-5691-478a-b333-97cc6fea7a69
- 판매자는 문의보다는 문의내용 확인이 우선이기 때문에 채팅 버튼을 눌렀을때 해당 상품의 모든 문의 내역 리스트를 먼저 보여준다.
2. chatList 유저일때 분기처리 완료
https://github.com/supercoding-commerce/FE/assets/100771469/f6bb53b5-f44d-40bd-8d42-d639be46728f
- 구매자는 상품에 대한 문의가 우선이기 때문에 채팅 버튼을 눌렀을때 해당 상품의 채팅창을 먼저 보여준다.
현재 유저와 판매자를 구분하는 isSeller는 하드코딩입니다.
추후 디테일페이지에서 isSeller값을 받아와서 처리할 예정입니다.
> feat:#103 chatList 판매자일때 / 유저일때 분기처리 완료

- src/components/FilterModal/FilterModal.styles.tsx
- src/components/FilterModal/FilterModal.tsx
- src/components/MainPage/ListItemComponent/AllProductList.tsx
- src/components/MainPage/ListItemComponent/ListItem.tsx
- src/components/MainPage/MainPage.styles.tsx
- src/components/MainPage/Swiper/BannerSwiper.styles.tsx
- src/components/MainPage/Swiper/BannerSwiper.tsx
- src/pages/ProductPage/CategoryList.tsx
- src/pages/ProductPage/ProductPage.styles.tsx
- src/pages/ProductPage/ProductPage.tsx
close #108 
스크롤바 스타일링
스와이퍼 스타일링
인피니트 스크롤 상품 클릭시 해당 상품으로 라우팅구현
> feat: mainpage 라우팅, 스크를바, 스와이퍼스타일링 완료

- src/apis/index.ts
- src/constants/index.ts
- src/pages/SignInPage/SignInPage.tsx
close #112 
- accessToken 과 refreshToken을 요청 시에 같이 보낼 수 있도록 로직 구현
> Refactor : 토큰 처리 부분 로직 수정

- src/App.tsx
- src/components/chat/Chat.styles.tsx
- src/components/chat/ChatButton.tsx
- src/pages/DetailPage/DetailPage.tsx
close #97 
chat detailPage에 채팅 버튼 추가 완료
https://github.com/supercoding-commerce/FE/assets/100771469/d0a12a26-d1da-4333-919a-065bb4070775
> feat:chat detailPage에 채팅 버튼 추가 완료

- src/pages/routes.tsx
> fix : 잘못된 프로덕트 상세 페이지 라우팅 url 변경

- src/assets/icon/Smile.svg
- src/assets/icon/index.ts
- src/components/chat/Chat.styles.tsx
- src/components/chat/Chat.tsx
- src/components/chat/ChatDetail.tsx
- src/components/chat/ChatList.tsx
- src/components/chat/chatDetail/ChatDetailBody.tsx
- src/components/chat/chatDetail/ChatLeftBox.tsx
- src/components/chat/chatDetail/ChatSend.tsx
- src/components/chat/chatList/ChatHeader.tsx
- src/pages/DetailPage/DetailPage.tsx
채팅 입력창 form으로 변경 완료
1. form으로 변경해서 엔터를 쳐도 메세지가 전달되도록 변경
2. 메세지 전달 후 채팅 인풋 초기화
> feat:채팅 입력창 form으로 변경 완료

- src/assets/icon/Smile.svg
- src/assets/icon/index.ts
- src/components/chat/Chat.styles.tsx
- src/components/chat/Chat.tsx
- src/components/chat/ChatDetail.tsx
- src/components/chat/ChatList.tsx
- src/components/chat/chatDetail/ChatDetailBody.tsx
- src/components/chat/chatDetail/ChatLeftBox.tsx
- src/components/chat/chatList/ChatHeader.tsx
- src/pages/DetailPage/DetailPage.tsx
1. 채팅 스크롤 화면에서 없애기
2. 채팅 리스트 +버튼 x버튼으로 수정하기
3. 채팅방 유저 이미지 반영하기
4. 최신 채팅 위치 바라보게 하기
1. 채팅 스크롤 화면에서 없앴습니다. (x쪽 포함)
2. 채팅 리스트 +버튼 x버튼으로 수정 후 클릭하면 채팅창 닫기게끔 수정했습니다.
3.  채팅방에 채팅 옆에 달리는 이미지는 [ 유저입장:해당샵 이미지 / 판매자입장:스마일 아이콘 ] 적용했습니다.
4. 채팅을 치거나 채팅방에 들어갔을때 최신 채팅 위치 바라보게 수정했습니다.
> feat:채팅 css 수정[아직 한가지 남음 리뷰x]

- src/apis/mypage.ts
- src/components/Mypage-Purchase/Purchase.styles.tsx
- src/components/Mypage-Purchase/Purchase.tsx
- src/components/common/Header/Header.tsx
- src/pages/routes.tsx
- src/styles/theme.ts
close #148 
구매이력 UI, API, image/productName 클릭 시 해당 product 페이지로 이동
> feat : mypage 구매이력

- src/components/common/Header/Header.tsx
- src/pages/Search/SearchProduct.tsx
- src/pages/routes.tsx
- routes.tsx파일 변경사항
{
path: '/product/search/category',
element: <ProductPage />,
},
{
path: '/product/search',
element: <SearchProduct />,
},
- Header.tsx파일 변경사항
NO_HEADER_URL에   '/product/search', 추가
> feat: searchProduct파일 생성 및 라우팅 재설정

- src/apis/categoryProduct.ts
- src/pages/Category/Menu.tsx
- src/pages/ProductPage/CategoryList.tsx
- src/pages/ProductPage/ProductPage.tsx
- src/pages/routes.tsx
- searchWord props 추가
- searchWord값에 따른 api통신 로직 변경
> feat: 키워드별 api통신로직 변경 ProductPage props부분 수정

- src/apis/mypage.ts
- src/components/Mypage-Sold/SoldPage.styles.tsx
- src/components/Mypage-Sold/SoldPage.tsx
- src/components/common/Header/Header.tsx
- src/pages/routes.tsx
- src/styles/theme.ts
close #150 
판매내역 UI, API, image/productName 클릭 시 해당 product 페이지로 이동
header 아래 쇼핑몰 이름을 넣을까 고민입니다!!
> feat : 판매내역

- src/components/common/Header/SearchHeader.tsx
> feat: mainpage header에 검색아이콘 클릭시 라우팅 추가 

- src/pages/CartPage/CartItem.styles.tsx
- src/pages/CartPage/CartPage.styles.tsx
- src/pages/CartPage/CartPage.tsx
close #145 
cartPage 수정
cart item 없을 시 
- 구매하기 버튼 disabled
- 장바구니에 담긴 상품이 없습니다. 보여주기
cart page css 수정
> feat : cartPage 수정

- src/components/chat/Chat.tsx
- src/components/chat/ChatDetail.tsx
- src/components/chat/chatDetail/ChatDetailBody.tsx
- src/components/chat/chatDetail/ChatDetailIntro.tsx
- src/components/chat/chatDetail/ChatLeftBox.tsx
- src/pages/DetailPage/DetailPage.tsx
close #144 
chat css 수정 - 채팅방 구매자 입장에서 판매자 이미지 반영하기
> feat:#144 채팅방 판매자  이미지 반영하기

- src/components/DetailFooter/DetailFooter.tsx
close #181 
userInfo가 'SELLER'일 때 'USER'일 때 구분해서 분기 처리
> feat : detail page footer 분기 처리

- src/components/DetailFooter/DetailFooter.tsx
- src/components/Mypage-Wish/WishItems.styles.tsx
- src/components/Mypage-Wish/WishPage.styles.tsx
- src/components/Mypage-Wish/WishPage.tsx
- src/pages/DetailPage/DetailPage.tsx
close #180 
상세 페이지에서도 heart API 연동
wishList get productId = product get productId 추가
> fix : 상세 페이지에서 heart 유지 X

- src/pages/DetailPage/DetailPage.tsx
close #171 
디테일페이지 상품상세/리뷰 버튼을 눌렀을때
상품상세 클릭 -> 리뷰내용 보임
리뷰 클릭 -> 상세정보 보임
상품상세 클릭 -> 상품상세 보임 완료
리뷰 클릭 -> 리뷰 보임 완료
> fix: 디테일페이지 상품상세/리뷰 버튼 잘못된 내용 보여짐 완료

- src/pages/Coupon/Coupon.styles.tsx
- src/pages/Coupon/Coupon.tsx
> feat:#189 마이페이지 쿠폰 css 수정완료

- src/hooks/useDebounce.ts
- src/pages/Search/Search.tsx
- src/pages/Search/SearchList.styles.tsx
- src/pages/Search/SearchList.tsx
-  디바운스를 이용한 키워드검색 기능 구현
-  hooks로 코드정리
-  키워드검색 리스트 css스타일링 적용
> feat: search페이지 추가사항 디바운스를 이용한 키워드검색 기능 구현

- src/apis/cart.ts
- src/apis/order.ts
- src/components/DetailFooter/DetailFooter.tsx
- src/pages/CartPage/CartPage.tsx
- src/pages/Payment/Payment.tsx
- src/queries/order/query.ts
close #156 
- 기존 주문 api 기능 구현 완료
> feat : 주문 api 기능 구현 완료

- src/apis/paymoney.ts
- src/pages/MyPage/MyPage.tsx
- src/pages/PayMoney/PayMoneyPage.tsx
close #185 
paymoney API 연동
paymoney API 연동
> feat : paymoney API 연동
